// This file is generated by rust-protobuf 2.18.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![rustfmt::skip]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `service.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_18_0;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct ChunkMetadata {
    // message fields
    pub time_range: ::protobuf::SingularPtrField<TimeRange>,
    pub offset: ::std::option::Option<u32>,
    pub length: ::std::option::Option<u32>,
    pub trace_offsets: ::std::vec::Vec<u32>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ChunkMetadata {
    fn default() -> &'a ChunkMetadata {
        <ChunkMetadata as ::protobuf::Message>::default_instance()
    }
}

impl ChunkMetadata {
    pub fn new() -> ChunkMetadata {
        ::std::default::Default::default()
    }

    // required .TimeRange time_range = 1;


    pub fn get_time_range(&self) -> &TimeRange {
        self.time_range.as_ref().unwrap_or_else(|| <TimeRange as ::protobuf::Message>::default_instance())
    }
    pub fn clear_time_range(&mut self) {
        self.time_range.clear();
    }

    pub fn has_time_range(&self) -> bool {
        self.time_range.is_some()
    }

    // Param is passed by value, moved
    pub fn set_time_range(&mut self, v: TimeRange) {
        self.time_range = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_time_range(&mut self) -> &mut TimeRange {
        if self.time_range.is_none() {
            self.time_range.set_default();
        }
        self.time_range.as_mut().unwrap()
    }

    // Take field
    pub fn take_time_range(&mut self) -> TimeRange {
        self.time_range.take().unwrap_or_else(|| TimeRange::new())
    }

    // required uint32 offset = 2;


    pub fn get_offset(&self) -> u32 {
        self.offset.unwrap_or(0)
    }
    pub fn clear_offset(&mut self) {
        self.offset = ::std::option::Option::None;
    }

    pub fn has_offset(&self) -> bool {
        self.offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_offset(&mut self, v: u32) {
        self.offset = ::std::option::Option::Some(v);
    }

    // required uint32 length = 3;


    pub fn get_length(&self) -> u32 {
        self.length.unwrap_or(0)
    }
    pub fn clear_length(&mut self) {
        self.length = ::std::option::Option::None;
    }

    pub fn has_length(&self) -> bool {
        self.length.is_some()
    }

    // Param is passed by value, moved
    pub fn set_length(&mut self, v: u32) {
        self.length = ::std::option::Option::Some(v);
    }

    // repeated uint32 trace_offsets = 4;


    pub fn get_trace_offsets(&self) -> &[u32] {
        &self.trace_offsets
    }
    pub fn clear_trace_offsets(&mut self) {
        self.trace_offsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_trace_offsets(&mut self, v: ::std::vec::Vec<u32>) {
        self.trace_offsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_trace_offsets(&mut self) -> &mut ::std::vec::Vec<u32> {
        &mut self.trace_offsets
    }

    // Take field
    pub fn take_trace_offsets(&mut self) -> ::std::vec::Vec<u32> {
        ::std::mem::replace(&mut self.trace_offsets, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for ChunkMetadata {
    fn is_initialized(&self) -> bool {
        if self.time_range.is_none() {
            return false;
        }
        if self.offset.is_none() {
            return false;
        }
        if self.length.is_none() {
            return false;
        }
        for v in &self.time_range {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.time_range)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.offset = ::std::option::Option::Some(tmp);
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.length = ::std::option::Option::Some(tmp);
                },
                4 => {
                    ::protobuf::rt::read_repeated_uint32_into(wire_type, is, &mut self.trace_offsets)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.time_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(v) = self.offset {
            my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.length {
            my_size += ::protobuf::rt::value_size(3, v, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.trace_offsets {
            my_size += ::protobuf::rt::value_size(4, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.time_range.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(v) = self.offset {
            os.write_uint32(2, v)?;
        }
        if let Some(v) = self.length {
            os.write_uint32(3, v)?;
        }
        for v in &self.trace_offsets {
            os.write_uint32(4, *v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ChunkMetadata {
        ChunkMetadata::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TimeRange>>(
                "time_range",
                |m: &ChunkMetadata| { &m.time_range },
                |m: &mut ChunkMetadata| { &mut m.time_range },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "offset",
                |m: &ChunkMetadata| { &m.offset },
                |m: &mut ChunkMetadata| { &mut m.offset },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "length",
                |m: &ChunkMetadata| { &m.length },
                |m: &mut ChunkMetadata| { &mut m.length },
            ));
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "trace_offsets",
                |m: &ChunkMetadata| { &m.trace_offsets },
                |m: &mut ChunkMetadata| { &mut m.trace_offsets },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ChunkMetadata>(
                "ChunkMetadata",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ChunkMetadata {
        static instance: ::protobuf::rt::LazyV2<ChunkMetadata> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ChunkMetadata::new)
    }
}

impl ::protobuf::Clear for ChunkMetadata {
    fn clear(&mut self) {
        self.time_range.clear();
        self.offset = ::std::option::Option::None;
        self.length = ::std::option::Option::None;
        self.trace_offsets.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ChunkMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ChunkMetadata {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct TraceIDOffset {
    // message fields
    pub offset: ::std::option::Option<u32>,
    pub hashed_trace_id: ::std::option::Option<u64>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TraceIDOffset {
    fn default() -> &'a TraceIDOffset {
        <TraceIDOffset as ::protobuf::Message>::default_instance()
    }
}

impl TraceIDOffset {
    pub fn new() -> TraceIDOffset {
        ::std::default::Default::default()
    }

    // required uint32 offset = 1;


    pub fn get_offset(&self) -> u32 {
        self.offset.unwrap_or(0)
    }
    pub fn clear_offset(&mut self) {
        self.offset = ::std::option::Option::None;
    }

    pub fn has_offset(&self) -> bool {
        self.offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_offset(&mut self, v: u32) {
        self.offset = ::std::option::Option::Some(v);
    }

    // required uint64 hashed_trace_id = 2;


    pub fn get_hashed_trace_id(&self) -> u64 {
        self.hashed_trace_id.unwrap_or(0)
    }
    pub fn clear_hashed_trace_id(&mut self) {
        self.hashed_trace_id = ::std::option::Option::None;
    }

    pub fn has_hashed_trace_id(&self) -> bool {
        self.hashed_trace_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_hashed_trace_id(&mut self, v: u64) {
        self.hashed_trace_id = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for TraceIDOffset {
    fn is_initialized(&self) -> bool {
        if self.offset.is_none() {
            return false;
        }
        if self.hashed_trace_id.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint32()?;
                    self.offset = ::std::option::Option::Some(tmp);
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.hashed_trace_id = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.offset {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.hashed_trace_id {
            my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.offset {
            os.write_uint32(1, v)?;
        }
        if let Some(v) = self.hashed_trace_id {
            os.write_uint64(2, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TraceIDOffset {
        TraceIDOffset::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint32>(
                "offset",
                |m: &TraceIDOffset| { &m.offset },
                |m: &mut TraceIDOffset| { &mut m.offset },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "hashed_trace_id",
                |m: &TraceIDOffset| { &m.hashed_trace_id },
                |m: &mut TraceIDOffset| { &mut m.hashed_trace_id },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TraceIDOffset>(
                "TraceIDOffset",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TraceIDOffset {
        static instance: ::protobuf::rt::LazyV2<TraceIDOffset> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TraceIDOffset::new)
    }
}

impl ::protobuf::Clear for TraceIDOffset {
    fn clear(&mut self) {
        self.offset = ::std::option::Option::None;
        self.hashed_trace_id = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TraceIDOffset {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TraceIDOffset {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct TraceIds {
    // message fields
    pub trace_ids: ::std::vec::Vec<u64>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TraceIds {
    fn default() -> &'a TraceIds {
        <TraceIds as ::protobuf::Message>::default_instance()
    }
}

impl TraceIds {
    pub fn new() -> TraceIds {
        ::std::default::Default::default()
    }

    // repeated uint64 trace_ids = 1;


    pub fn get_trace_ids(&self) -> &[u64] {
        &self.trace_ids
    }
    pub fn clear_trace_ids(&mut self) {
        self.trace_ids.clear();
    }

    // Param is passed by value, moved
    pub fn set_trace_ids(&mut self, v: ::std::vec::Vec<u64>) {
        self.trace_ids = v;
    }

    // Mutable pointer to the field.
    pub fn mut_trace_ids(&mut self) -> &mut ::std::vec::Vec<u64> {
        &mut self.trace_ids
    }

    // Take field
    pub fn take_trace_ids(&mut self) -> ::std::vec::Vec<u64> {
        ::std::mem::replace(&mut self.trace_ids, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for TraceIds {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_uint64_into(wire_type, is, &mut self.trace_ids)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.trace_ids {
            my_size += ::protobuf::rt::value_size(1, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.trace_ids {
            os.write_uint64(1, *v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TraceIds {
        TraceIds::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "trace_ids",
                |m: &TraceIds| { &m.trace_ids },
                |m: &mut TraceIds| { &mut m.trace_ids },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TraceIds>(
                "TraceIds",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TraceIds {
        static instance: ::protobuf::rt::LazyV2<TraceIds> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TraceIds::new)
    }
}

impl ::protobuf::Clear for TraceIds {
    fn clear(&mut self) {
        self.trace_ids.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TraceIds {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TraceIds {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct WalOffsets {
    // message fields
    pub offsets: ::std::vec::Vec<u64>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a WalOffsets {
    fn default() -> &'a WalOffsets {
        <WalOffsets as ::protobuf::Message>::default_instance()
    }
}

impl WalOffsets {
    pub fn new() -> WalOffsets {
        ::std::default::Default::default()
    }

    // repeated uint64 offsets = 1;


    pub fn get_offsets(&self) -> &[u64] {
        &self.offsets
    }
    pub fn clear_offsets(&mut self) {
        self.offsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_offsets(&mut self, v: ::std::vec::Vec<u64>) {
        self.offsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_offsets(&mut self) -> &mut ::std::vec::Vec<u64> {
        &mut self.offsets
    }

    // Take field
    pub fn take_offsets(&mut self) -> ::std::vec::Vec<u64> {
        ::std::mem::replace(&mut self.offsets, ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for WalOffsets {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_uint64_into(wire_type, is, &mut self.offsets)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.offsets {
            my_size += ::protobuf::rt::value_size(1, *value, ::protobuf::wire_format::WireTypeVarint);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.offsets {
            os.write_uint64(1, *v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> WalOffsets {
        WalOffsets::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_vec_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "offsets",
                |m: &WalOffsets| { &m.offsets },
                |m: &mut WalOffsets| { &mut m.offsets },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<WalOffsets>(
                "WalOffsets",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static WalOffsets {
        static instance: ::protobuf::rt::LazyV2<WalOffsets> = ::protobuf::rt::LazyV2::INIT;
        instance.get(WalOffsets::new)
    }
}

impl ::protobuf::Clear for WalOffsets {
    fn clear(&mut self) {
        self.offsets.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for WalOffsets {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for WalOffsets {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct SegmentMetadata {
    // message fields
    pub time_range: ::protobuf::SingularPtrField<TimeRange>,
    pub chunks: ::protobuf::RepeatedField<ChunkMetadata>,
    pub index: ::std::collections::HashMap<::std::string::String, TraceIds>,
    pub sorted_trace_ids: ::protobuf::RepeatedField<TraceIDOffset>,
    pub delayed_span_wal_offsets: ::std::collections::HashMap<u64, WalOffsets>,
    pub max_wal_id: ::std::option::Option<u64>,
    pub max_wal_offset: ::std::option::Option<u64>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a SegmentMetadata {
    fn default() -> &'a SegmentMetadata {
        <SegmentMetadata as ::protobuf::Message>::default_instance()
    }
}

impl SegmentMetadata {
    pub fn new() -> SegmentMetadata {
        ::std::default::Default::default()
    }

    // required .TimeRange time_range = 1;


    pub fn get_time_range(&self) -> &TimeRange {
        self.time_range.as_ref().unwrap_or_else(|| <TimeRange as ::protobuf::Message>::default_instance())
    }
    pub fn clear_time_range(&mut self) {
        self.time_range.clear();
    }

    pub fn has_time_range(&self) -> bool {
        self.time_range.is_some()
    }

    // Param is passed by value, moved
    pub fn set_time_range(&mut self, v: TimeRange) {
        self.time_range = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_time_range(&mut self) -> &mut TimeRange {
        if self.time_range.is_none() {
            self.time_range.set_default();
        }
        self.time_range.as_mut().unwrap()
    }

    // Take field
    pub fn take_time_range(&mut self) -> TimeRange {
        self.time_range.take().unwrap_or_else(|| TimeRange::new())
    }

    // repeated .ChunkMetadata chunks = 2;


    pub fn get_chunks(&self) -> &[ChunkMetadata] {
        &self.chunks
    }
    pub fn clear_chunks(&mut self) {
        self.chunks.clear();
    }

    // Param is passed by value, moved
    pub fn set_chunks(&mut self, v: ::protobuf::RepeatedField<ChunkMetadata>) {
        self.chunks = v;
    }

    // Mutable pointer to the field.
    pub fn mut_chunks(&mut self) -> &mut ::protobuf::RepeatedField<ChunkMetadata> {
        &mut self.chunks
    }

    // Take field
    pub fn take_chunks(&mut self) -> ::protobuf::RepeatedField<ChunkMetadata> {
        ::std::mem::replace(&mut self.chunks, ::protobuf::RepeatedField::new())
    }

    // repeated .SegmentMetadata.IndexEntry index = 3;


    pub fn get_index(&self) -> &::std::collections::HashMap<::std::string::String, TraceIds> {
        &self.index
    }
    pub fn clear_index(&mut self) {
        self.index.clear();
    }

    // Param is passed by value, moved
    pub fn set_index(&mut self, v: ::std::collections::HashMap<::std::string::String, TraceIds>) {
        self.index = v;
    }

    // Mutable pointer to the field.
    pub fn mut_index(&mut self) -> &mut ::std::collections::HashMap<::std::string::String, TraceIds> {
        &mut self.index
    }

    // Take field
    pub fn take_index(&mut self) -> ::std::collections::HashMap<::std::string::String, TraceIds> {
        ::std::mem::replace(&mut self.index, ::std::collections::HashMap::new())
    }

    // repeated .TraceIDOffset sorted_trace_ids = 4;


    pub fn get_sorted_trace_ids(&self) -> &[TraceIDOffset] {
        &self.sorted_trace_ids
    }
    pub fn clear_sorted_trace_ids(&mut self) {
        self.sorted_trace_ids.clear();
    }

    // Param is passed by value, moved
    pub fn set_sorted_trace_ids(&mut self, v: ::protobuf::RepeatedField<TraceIDOffset>) {
        self.sorted_trace_ids = v;
    }

    // Mutable pointer to the field.
    pub fn mut_sorted_trace_ids(&mut self) -> &mut ::protobuf::RepeatedField<TraceIDOffset> {
        &mut self.sorted_trace_ids
    }

    // Take field
    pub fn take_sorted_trace_ids(&mut self) -> ::protobuf::RepeatedField<TraceIDOffset> {
        ::std::mem::replace(&mut self.sorted_trace_ids, ::protobuf::RepeatedField::new())
    }

    // repeated .SegmentMetadata.DelayedSpanWalOffsetsEntry delayed_span_wal_offsets = 5;


    pub fn get_delayed_span_wal_offsets(&self) -> &::std::collections::HashMap<u64, WalOffsets> {
        &self.delayed_span_wal_offsets
    }
    pub fn clear_delayed_span_wal_offsets(&mut self) {
        self.delayed_span_wal_offsets.clear();
    }

    // Param is passed by value, moved
    pub fn set_delayed_span_wal_offsets(&mut self, v: ::std::collections::HashMap<u64, WalOffsets>) {
        self.delayed_span_wal_offsets = v;
    }

    // Mutable pointer to the field.
    pub fn mut_delayed_span_wal_offsets(&mut self) -> &mut ::std::collections::HashMap<u64, WalOffsets> {
        &mut self.delayed_span_wal_offsets
    }

    // Take field
    pub fn take_delayed_span_wal_offsets(&mut self) -> ::std::collections::HashMap<u64, WalOffsets> {
        ::std::mem::replace(&mut self.delayed_span_wal_offsets, ::std::collections::HashMap::new())
    }

    // required uint64 max_wal_id = 6;


    pub fn get_max_wal_id(&self) -> u64 {
        self.max_wal_id.unwrap_or(0)
    }
    pub fn clear_max_wal_id(&mut self) {
        self.max_wal_id = ::std::option::Option::None;
    }

    pub fn has_max_wal_id(&self) -> bool {
        self.max_wal_id.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_wal_id(&mut self, v: u64) {
        self.max_wal_id = ::std::option::Option::Some(v);
    }

    // required uint64 max_wal_offset = 7;


    pub fn get_max_wal_offset(&self) -> u64 {
        self.max_wal_offset.unwrap_or(0)
    }
    pub fn clear_max_wal_offset(&mut self) {
        self.max_wal_offset = ::std::option::Option::None;
    }

    pub fn has_max_wal_offset(&self) -> bool {
        self.max_wal_offset.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_wal_offset(&mut self, v: u64) {
        self.max_wal_offset = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for SegmentMetadata {
    fn is_initialized(&self) -> bool {
        if self.time_range.is_none() {
            return false;
        }
        if self.max_wal_id.is_none() {
            return false;
        }
        if self.max_wal_offset.is_none() {
            return false;
        }
        for v in &self.time_range {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.chunks {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.sorted_trace_ids {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.time_range)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.chunks)?;
                },
                3 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<TraceIds>>(wire_type, is, &mut self.index)?;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.sorted_trace_ids)?;
                },
                5 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeUint64, ::protobuf::types::ProtobufTypeMessage<WalOffsets>>(wire_type, is, &mut self.delayed_span_wal_offsets)?;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.max_wal_id = ::std::option::Option::Some(tmp);
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.max_wal_offset = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.time_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        for value in &self.chunks {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<TraceIds>>(3, &self.index);
        for value in &self.sorted_trace_ids {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeUint64, ::protobuf::types::ProtobufTypeMessage<WalOffsets>>(5, &self.delayed_span_wal_offsets);
        if let Some(v) = self.max_wal_id {
            my_size += ::protobuf::rt::value_size(6, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.max_wal_offset {
            my_size += ::protobuf::rt::value_size(7, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.time_range.as_ref() {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        for v in &self.chunks {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<TraceIds>>(3, &self.index, os)?;
        for v in &self.sorted_trace_ids {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeUint64, ::protobuf::types::ProtobufTypeMessage<WalOffsets>>(5, &self.delayed_span_wal_offsets, os)?;
        if let Some(v) = self.max_wal_id {
            os.write_uint64(6, v)?;
        }
        if let Some(v) = self.max_wal_offset {
            os.write_uint64(7, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> SegmentMetadata {
        SegmentMetadata::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TimeRange>>(
                "time_range",
                |m: &SegmentMetadata| { &m.time_range },
                |m: &mut SegmentMetadata| { &mut m.time_range },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<ChunkMetadata>>(
                "chunks",
                |m: &SegmentMetadata| { &m.chunks },
                |m: &mut SegmentMetadata| { &mut m.chunks },
            ));
            fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<TraceIds>>(
                "index",
                |m: &SegmentMetadata| { &m.index },
                |m: &mut SegmentMetadata| { &mut m.index },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TraceIDOffset>>(
                "sorted_trace_ids",
                |m: &SegmentMetadata| { &m.sorted_trace_ids },
                |m: &mut SegmentMetadata| { &mut m.sorted_trace_ids },
            ));
            fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeUint64, ::protobuf::types::ProtobufTypeMessage<WalOffsets>>(
                "delayed_span_wal_offsets",
                |m: &SegmentMetadata| { &m.delayed_span_wal_offsets },
                |m: &mut SegmentMetadata| { &mut m.delayed_span_wal_offsets },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "max_wal_id",
                |m: &SegmentMetadata| { &m.max_wal_id },
                |m: &mut SegmentMetadata| { &mut m.max_wal_id },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "max_wal_offset",
                |m: &SegmentMetadata| { &m.max_wal_offset },
                |m: &mut SegmentMetadata| { &mut m.max_wal_offset },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<SegmentMetadata>(
                "SegmentMetadata",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static SegmentMetadata {
        static instance: ::protobuf::rt::LazyV2<SegmentMetadata> = ::protobuf::rt::LazyV2::INIT;
        instance.get(SegmentMetadata::new)
    }
}

impl ::protobuf::Clear for SegmentMetadata {
    fn clear(&mut self) {
        self.time_range.clear();
        self.chunks.clear();
        self.index.clear();
        self.sorted_trace_ids.clear();
        self.delayed_span_wal_offsets.clear();
        self.max_wal_id = ::std::option::Option::None;
        self.max_wal_offset = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for SegmentMetadata {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for SegmentMetadata {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct QueryRequest {
    // message fields
    pub service_name: ::protobuf::SingularField<::std::string::String>,
    pub operation_name: ::protobuf::SingularField<::std::string::String>,
    pub tags: ::std::collections::HashMap<::std::string::String, ::std::string::String>,
    pub time_range: ::protobuf::SingularPtrField<TimeRange>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a QueryRequest {
    fn default() -> &'a QueryRequest {
        <QueryRequest as ::protobuf::Message>::default_instance()
    }
}

impl QueryRequest {
    pub fn new() -> QueryRequest {
        ::std::default::Default::default()
    }

    // optional string service_name = 1;


    pub fn get_service_name(&self) -> &str {
        match self.service_name.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_service_name(&mut self) {
        self.service_name.clear();
    }

    pub fn has_service_name(&self) -> bool {
        self.service_name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_service_name(&mut self, v: ::std::string::String) {
        self.service_name = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_service_name(&mut self) -> &mut ::std::string::String {
        if self.service_name.is_none() {
            self.service_name.set_default();
        }
        self.service_name.as_mut().unwrap()
    }

    // Take field
    pub fn take_service_name(&mut self) -> ::std::string::String {
        self.service_name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // optional string operation_name = 2;


    pub fn get_operation_name(&self) -> &str {
        match self.operation_name.as_ref() {
            Some(v) => &v,
            None => "",
        }
    }
    pub fn clear_operation_name(&mut self) {
        self.operation_name.clear();
    }

    pub fn has_operation_name(&self) -> bool {
        self.operation_name.is_some()
    }

    // Param is passed by value, moved
    pub fn set_operation_name(&mut self, v: ::std::string::String) {
        self.operation_name = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_operation_name(&mut self) -> &mut ::std::string::String {
        if self.operation_name.is_none() {
            self.operation_name.set_default();
        }
        self.operation_name.as_mut().unwrap()
    }

    // Take field
    pub fn take_operation_name(&mut self) -> ::std::string::String {
        self.operation_name.take().unwrap_or_else(|| ::std::string::String::new())
    }

    // repeated .QueryRequest.TagsEntry tags = 3;


    pub fn get_tags(&self) -> &::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &self.tags
    }
    pub fn clear_tags(&mut self) {
        self.tags.clear();
    }

    // Param is passed by value, moved
    pub fn set_tags(&mut self, v: ::std::collections::HashMap<::std::string::String, ::std::string::String>) {
        self.tags = v;
    }

    // Mutable pointer to the field.
    pub fn mut_tags(&mut self) -> &mut ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        &mut self.tags
    }

    // Take field
    pub fn take_tags(&mut self) -> ::std::collections::HashMap<::std::string::String, ::std::string::String> {
        ::std::mem::replace(&mut self.tags, ::std::collections::HashMap::new())
    }

    // required .TimeRange time_range = 4;


    pub fn get_time_range(&self) -> &TimeRange {
        self.time_range.as_ref().unwrap_or_else(|| <TimeRange as ::protobuf::Message>::default_instance())
    }
    pub fn clear_time_range(&mut self) {
        self.time_range.clear();
    }

    pub fn has_time_range(&self) -> bool {
        self.time_range.is_some()
    }

    // Param is passed by value, moved
    pub fn set_time_range(&mut self, v: TimeRange) {
        self.time_range = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_time_range(&mut self) -> &mut TimeRange {
        if self.time_range.is_none() {
            self.time_range.set_default();
        }
        self.time_range.as_mut().unwrap()
    }

    // Take field
    pub fn take_time_range(&mut self) -> TimeRange {
        self.time_range.take().unwrap_or_else(|| TimeRange::new())
    }
}

impl ::protobuf::Message for QueryRequest {
    fn is_initialized(&self) -> bool {
        if self.time_range.is_none() {
            return false;
        }
        for v in &self.time_range {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.service_name)?;
                },
                2 => {
                    ::protobuf::rt::read_singular_string_into(wire_type, is, &mut self.operation_name)?;
                },
                3 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(wire_type, is, &mut self.tags)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.time_range)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(ref v) = self.service_name.as_ref() {
            my_size += ::protobuf::rt::string_size(1, &v);
        }
        if let Some(ref v) = self.operation_name.as_ref() {
            my_size += ::protobuf::rt::string_size(2, &v);
        }
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(3, &self.tags);
        if let Some(ref v) = self.time_range.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(ref v) = self.service_name.as_ref() {
            os.write_string(1, &v)?;
        }
        if let Some(ref v) = self.operation_name.as_ref() {
            os.write_string(2, &v)?;
        }
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(3, &self.tags, os)?;
        if let Some(ref v) = self.time_range.as_ref() {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> QueryRequest {
        QueryRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "service_name",
                |m: &QueryRequest| { &m.service_name },
                |m: &mut QueryRequest| { &mut m.service_name },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "operation_name",
                |m: &QueryRequest| { &m.operation_name },
                |m: &mut QueryRequest| { &mut m.operation_name },
            ));
            fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeString>(
                "tags",
                |m: &QueryRequest| { &m.tags },
                |m: &mut QueryRequest| { &mut m.tags },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<TimeRange>>(
                "time_range",
                |m: &QueryRequest| { &m.time_range },
                |m: &mut QueryRequest| { &mut m.time_range },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<QueryRequest>(
                "QueryRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static QueryRequest {
        static instance: ::protobuf::rt::LazyV2<QueryRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(QueryRequest::new)
    }
}

impl ::protobuf::Clear for QueryRequest {
    fn clear(&mut self) {
        self.service_name.clear();
        self.operation_name.clear();
        self.tags.clear();
        self.time_range.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for QueryRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for QueryRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct TimeRange {
    // message fields
    pub min_start_ts: ::std::option::Option<u64>,
    pub max_start_ts: ::std::option::Option<u64>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TimeRange {
    fn default() -> &'a TimeRange {
        <TimeRange as ::protobuf::Message>::default_instance()
    }
}

impl TimeRange {
    pub fn new() -> TimeRange {
        ::std::default::Default::default()
    }

    // required uint64 min_start_ts = 1;


    pub fn get_min_start_ts(&self) -> u64 {
        self.min_start_ts.unwrap_or(0)
    }
    pub fn clear_min_start_ts(&mut self) {
        self.min_start_ts = ::std::option::Option::None;
    }

    pub fn has_min_start_ts(&self) -> bool {
        self.min_start_ts.is_some()
    }

    // Param is passed by value, moved
    pub fn set_min_start_ts(&mut self, v: u64) {
        self.min_start_ts = ::std::option::Option::Some(v);
    }

    // required uint64 max_start_ts = 2;


    pub fn get_max_start_ts(&self) -> u64 {
        self.max_start_ts.unwrap_or(0)
    }
    pub fn clear_max_start_ts(&mut self) {
        self.max_start_ts = ::std::option::Option::None;
    }

    pub fn has_max_start_ts(&self) -> bool {
        self.max_start_ts.is_some()
    }

    // Param is passed by value, moved
    pub fn set_max_start_ts(&mut self, v: u64) {
        self.max_start_ts = ::std::option::Option::Some(v);
    }
}

impl ::protobuf::Message for TimeRange {
    fn is_initialized(&self) -> bool {
        if self.min_start_ts.is_none() {
            return false;
        }
        if self.max_start_ts.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.min_start_ts = ::std::option::Option::Some(tmp);
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.max_start_ts = ::std::option::Option::Some(tmp);
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.min_start_ts {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(v) = self.max_start_ts {
            my_size += ::protobuf::rt::value_size(2, v, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.min_start_ts {
            os.write_uint64(1, v)?;
        }
        if let Some(v) = self.max_start_ts {
            os.write_uint64(2, v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TimeRange {
        TimeRange::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "min_start_ts",
                |m: &TimeRange| { &m.min_start_ts },
                |m: &mut TimeRange| { &mut m.min_start_ts },
            ));
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "max_start_ts",
                |m: &TimeRange| { &m.max_start_ts },
                |m: &mut TimeRange| { &mut m.max_start_ts },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TimeRange>(
                "TimeRange",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TimeRange {
        static instance: ::protobuf::rt::LazyV2<TimeRange> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TimeRange::new)
    }
}

impl ::protobuf::Clear for TimeRange {
    fn clear(&mut self) {
        self.min_start_ts = ::std::option::Option::None;
        self.max_start_ts = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TimeRange {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TimeRange {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct InternalTrace {
    // message fields
    pub start_ts: ::std::option::Option<u64>,
    pub trace: ::protobuf::SingularField<::std::vec::Vec<u8>>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a InternalTrace {
    fn default() -> &'a InternalTrace {
        <InternalTrace as ::protobuf::Message>::default_instance()
    }
}

impl InternalTrace {
    pub fn new() -> InternalTrace {
        ::std::default::Default::default()
    }

    // required uint64 start_ts = 1;


    pub fn get_start_ts(&self) -> u64 {
        self.start_ts.unwrap_or(0)
    }
    pub fn clear_start_ts(&mut self) {
        self.start_ts = ::std::option::Option::None;
    }

    pub fn has_start_ts(&self) -> bool {
        self.start_ts.is_some()
    }

    // Param is passed by value, moved
    pub fn set_start_ts(&mut self, v: u64) {
        self.start_ts = ::std::option::Option::Some(v);
    }

    // required bytes trace = 2;


    pub fn get_trace(&self) -> &[u8] {
        match self.trace.as_ref() {
            Some(v) => &v,
            None => &[],
        }
    }
    pub fn clear_trace(&mut self) {
        self.trace.clear();
    }

    pub fn has_trace(&self) -> bool {
        self.trace.is_some()
    }

    // Param is passed by value, moved
    pub fn set_trace(&mut self, v: ::std::vec::Vec<u8>) {
        self.trace = ::protobuf::SingularField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_trace(&mut self) -> &mut ::std::vec::Vec<u8> {
        if self.trace.is_none() {
            self.trace.set_default();
        }
        self.trace.as_mut().unwrap()
    }

    // Take field
    pub fn take_trace(&mut self) -> ::std::vec::Vec<u8> {
        self.trace.take().unwrap_or_else(|| ::std::vec::Vec::new())
    }
}

impl ::protobuf::Message for InternalTrace {
    fn is_initialized(&self) -> bool {
        if self.start_ts.is_none() {
            return false;
        }
        if self.trace.is_none() {
            return false;
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_uint64()?;
                    self.start_ts = ::std::option::Option::Some(tmp);
                },
                2 => {
                    ::protobuf::rt::read_singular_bytes_into(wire_type, is, &mut self.trace)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let Some(v) = self.start_ts {
            my_size += ::protobuf::rt::value_size(1, v, ::protobuf::wire_format::WireTypeVarint);
        }
        if let Some(ref v) = self.trace.as_ref() {
            my_size += ::protobuf::rt::bytes_size(2, &v);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if let Some(v) = self.start_ts {
            os.write_uint64(1, v)?;
        }
        if let Some(ref v) = self.trace.as_ref() {
            os.write_bytes(2, &v)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> InternalTrace {
        InternalTrace::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_option_accessor::<_, ::protobuf::types::ProtobufTypeUint64>(
                "start_ts",
                |m: &InternalTrace| { &m.start_ts },
                |m: &mut InternalTrace| { &mut m.start_ts },
            ));
            fields.push(::protobuf::reflect::accessor::make_singular_field_accessor::<_, ::protobuf::types::ProtobufTypeBytes>(
                "trace",
                |m: &InternalTrace| { &m.trace },
                |m: &mut InternalTrace| { &mut m.trace },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<InternalTrace>(
                "InternalTrace",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static InternalTrace {
        static instance: ::protobuf::rt::LazyV2<InternalTrace> = ::protobuf::rt::LazyV2::INIT;
        instance.get(InternalTrace::new)
    }
}

impl ::protobuf::Clear for InternalTrace {
    fn clear(&mut self) {
        self.start_ts = ::std::option::Option::None;
        self.trace.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for InternalTrace {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for InternalTrace {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct QueryResponse {
    // message fields
    pub traces: ::protobuf::RepeatedField<InternalTrace>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a QueryResponse {
    fn default() -> &'a QueryResponse {
        <QueryResponse as ::protobuf::Message>::default_instance()
    }
}

impl QueryResponse {
    pub fn new() -> QueryResponse {
        ::std::default::Default::default()
    }

    // repeated .InternalTrace traces = 1;


    pub fn get_traces(&self) -> &[InternalTrace] {
        &self.traces
    }
    pub fn clear_traces(&mut self) {
        self.traces.clear();
    }

    // Param is passed by value, moved
    pub fn set_traces(&mut self, v: ::protobuf::RepeatedField<InternalTrace>) {
        self.traces = v;
    }

    // Mutable pointer to the field.
    pub fn mut_traces(&mut self) -> &mut ::protobuf::RepeatedField<InternalTrace> {
        &mut self.traces
    }

    // Take field
    pub fn take_traces(&mut self) -> ::protobuf::RepeatedField<InternalTrace> {
        ::std::mem::replace(&mut self.traces, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for QueryResponse {
    fn is_initialized(&self) -> bool {
        for v in &self.traces {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.traces)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.traces {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.traces {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> QueryResponse {
        QueryResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<InternalTrace>>(
                "traces",
                |m: &QueryResponse| { &m.traces },
                |m: &mut QueryResponse| { &mut m.traces },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<QueryResponse>(
                "QueryResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static QueryResponse {
        static instance: ::protobuf::rt::LazyV2<QueryResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(QueryResponse::new)
    }
}

impl ::protobuf::Clear for QueryResponse {
    fn clear(&mut self) {
        self.traces.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for QueryResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for QueryResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct TagRequest {
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TagRequest {
    fn default() -> &'a TagRequest {
        <TagRequest as ::protobuf::Message>::default_instance()
    }
}

impl TagRequest {
    pub fn new() -> TagRequest {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for TagRequest {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TagRequest {
        TagRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TagRequest>(
                "TagRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TagRequest {
        static instance: ::protobuf::rt::LazyV2<TagRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TagRequest::new)
    }
}

impl ::protobuf::Clear for TagRequest {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TagRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TagRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(Serialize, Deserialize))]
pub struct TagResponse {
    // message fields
    pub service_names: ::protobuf::RepeatedField<::std::string::String>,
    pub operation_names: ::protobuf::RepeatedField<::std::string::String>,
    pub instance_ids: ::protobuf::RepeatedField<::std::string::String>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a TagResponse {
    fn default() -> &'a TagResponse {
        <TagResponse as ::protobuf::Message>::default_instance()
    }
}

impl TagResponse {
    pub fn new() -> TagResponse {
        ::std::default::Default::default()
    }

    // repeated string service_names = 1;


    pub fn get_service_names(&self) -> &[::std::string::String] {
        &self.service_names
    }
    pub fn clear_service_names(&mut self) {
        self.service_names.clear();
    }

    // Param is passed by value, moved
    pub fn set_service_names(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.service_names = v;
    }

    // Mutable pointer to the field.
    pub fn mut_service_names(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.service_names
    }

    // Take field
    pub fn take_service_names(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.service_names, ::protobuf::RepeatedField::new())
    }

    // repeated string operation_names = 2;


    pub fn get_operation_names(&self) -> &[::std::string::String] {
        &self.operation_names
    }
    pub fn clear_operation_names(&mut self) {
        self.operation_names.clear();
    }

    // Param is passed by value, moved
    pub fn set_operation_names(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.operation_names = v;
    }

    // Mutable pointer to the field.
    pub fn mut_operation_names(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.operation_names
    }

    // Take field
    pub fn take_operation_names(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.operation_names, ::protobuf::RepeatedField::new())
    }

    // repeated string instance_ids = 3;


    pub fn get_instance_ids(&self) -> &[::std::string::String] {
        &self.instance_ids
    }
    pub fn clear_instance_ids(&mut self) {
        self.instance_ids.clear();
    }

    // Param is passed by value, moved
    pub fn set_instance_ids(&mut self, v: ::protobuf::RepeatedField<::std::string::String>) {
        self.instance_ids = v;
    }

    // Mutable pointer to the field.
    pub fn mut_instance_ids(&mut self) -> &mut ::protobuf::RepeatedField<::std::string::String> {
        &mut self.instance_ids
    }

    // Take field
    pub fn take_instance_ids(&mut self) -> ::protobuf::RepeatedField<::std::string::String> {
        ::std::mem::replace(&mut self.instance_ids, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for TagResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.service_names)?;
                },
                2 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.operation_names)?;
                },
                3 => {
                    ::protobuf::rt::read_repeated_string_into(wire_type, is, &mut self.instance_ids)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.service_names {
            my_size += ::protobuf::rt::string_size(1, &value);
        };
        for value in &self.operation_names {
            my_size += ::protobuf::rt::string_size(2, &value);
        };
        for value in &self.instance_ids {
            my_size += ::protobuf::rt::string_size(3, &value);
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.service_names {
            os.write_string(1, &v)?;
        };
        for v in &self.operation_names {
            os.write_string(2, &v)?;
        };
        for v in &self.instance_ids {
            os.write_string(3, &v)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> TagResponse {
        TagResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "service_names",
                |m: &TagResponse| { &m.service_names },
                |m: &mut TagResponse| { &mut m.service_names },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "operation_names",
                |m: &TagResponse| { &m.operation_names },
                |m: &mut TagResponse| { &mut m.operation_names },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "instance_ids",
                |m: &TagResponse| { &m.instance_ids },
                |m: &mut TagResponse| { &mut m.instance_ids },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<TagResponse>(
                "TagResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static TagResponse {
        static instance: ::protobuf::rt::LazyV2<TagResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(TagResponse::new)
    }
}

impl ::protobuf::Clear for TagResponse {
    fn clear(&mut self) {
        self.service_names.clear();
        self.operation_names.clear();
        self.instance_ids.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for TagResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for TagResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\rservice.proto\"\x8f\x01\n\rChunkMetadata\x12)\n\ntime_range\x18\x01\
    \x20\x02(\x0b2\n.TimeRangeR\ttimeRange\x12\x16\n\x06offset\x18\x02\x20\
    \x02(\rR\x06offset\x12\x16\n\x06length\x18\x03\x20\x02(\rR\x06length\x12\
    #\n\rtrace_offsets\x18\x04\x20\x03(\rR\x0ctraceOffsets\"O\n\rTraceIDOffs\
    et\x12\x16\n\x06offset\x18\x01\x20\x02(\rR\x06offset\x12&\n\x0fhashed_tr\
    ace_id\x18\x02\x20\x02(\x04R\rhashedTraceId\"'\n\x08TraceIds\x12\x1b\n\t\
    trace_ids\x18\x01\x20\x03(\x04R\x08traceIds\"&\n\nWalOffsets\x12\x18\n\
    \x07offsets\x18\x01\x20\x03(\x04R\x07offsets\"\x97\x04\n\x0fSegmentMetad\
    ata\x12)\n\ntime_range\x18\x01\x20\x02(\x0b2\n.TimeRangeR\ttimeRange\x12\
    &\n\x06chunks\x18\x02\x20\x03(\x0b2\x0e.ChunkMetadataR\x06chunks\x121\n\
    \x05index\x18\x03\x20\x03(\x0b2\x1b.SegmentMetadata.IndexEntryR\x05index\
    \x128\n\x10sorted_trace_ids\x18\x04\x20\x03(\x0b2\x0e.TraceIDOffsetR\x0e\
    sortedTraceIds\x12d\n\x18delayed_span_wal_offsets\x18\x05\x20\x03(\x0b2+\
    .SegmentMetadata.DelayedSpanWalOffsetsEntryR\x15delayedSpanWalOffsets\
    \x12\x1c\n\nmax_wal_id\x18\x06\x20\x02(\x04R\x08maxWalId\x12$\n\x0emax_w\
    al_offset\x18\x07\x20\x02(\x04R\x0cmaxWalOffset\x1aC\n\nIndexEntry\x12\
    \x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\x1f\n\x05value\x18\x02\x20\
    \x01(\x0b2\t.TraceIdsR\x05value:\x028\x01\x1aU\n\x1aDelayedSpanWalOffset\
    sEntry\x12\x10\n\x03key\x18\x01\x20\x01(\x04R\x03key\x12!\n\x05value\x18\
    \x02\x20\x01(\x0b2\x0b.WalOffsetsR\x05value:\x028\x01\"\xe9\x01\n\x0cQue\
    ryRequest\x12!\n\x0cservice_name\x18\x01\x20\x01(\tR\x0bserviceName\x12%\
    \n\x0eoperation_name\x18\x02\x20\x01(\tR\roperationName\x12+\n\x04tags\
    \x18\x03\x20\x03(\x0b2\x17.QueryRequest.TagsEntryR\x04tags\x12)\n\ntime_\
    range\x18\x04\x20\x02(\x0b2\n.TimeRangeR\ttimeRange\x1a7\n\tTagsEntry\
    \x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x12\x14\n\x05value\x18\x02\
    \x20\x01(\tR\x05value:\x028\x01\"O\n\tTimeRange\x12\x20\n\x0cmin_start_t\
    s\x18\x01\x20\x02(\x04R\nminStartTs\x12\x20\n\x0cmax_start_ts\x18\x02\
    \x20\x02(\x04R\nmaxStartTs\"@\n\rInternalTrace\x12\x19\n\x08start_ts\x18\
    \x01\x20\x02(\x04R\x07startTs\x12\x14\n\x05trace\x18\x02\x20\x02(\x0cR\
    \x05trace\"7\n\rQueryResponse\x12&\n\x06traces\x18\x01\x20\x03(\x0b2\x0e\
    .InternalTraceR\x06traces\"\x0c\n\nTagRequest\"~\n\x0bTagResponse\x12#\n\
    \rservice_names\x18\x01\x20\x03(\tR\x0cserviceNames\x12'\n\x0foperation_\
    names\x18\x02\x20\x03(\tR\x0eoperationNames\x12!\n\x0cinstance_ids\x18\
    \x03\x20\x03(\tR\x0binstanceIds2d\n\x0bSoduStorage\x12-\n\nQueryTrace\
    \x12\r.QueryRequest\x1a\x0e.QueryResponse\"\0\x12&\n\x07GetTags\x12\x0b.\
    TagRequest\x1a\x0c.TagResponse\"\0\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
